GitHub Action to lint Python code
TadaSoftware/PyNFe pull request #110
Opened 2021-05-14 08:47 UTC by cclauss

* `print()` is a function in Python 3.
* `basestring` and `unicode` were removed in Python 3.

2021-11-07 04:54 UTC, juniortada commented
@silvioprog faz MUITO tempo que estou devendo uma atualização completa no PyNFe com novos teste, lint, etc
para dar mais agilidade nas contribuições. Vou adicionar um workflow completo além de nova documentação para 
participantes que queriam contribuir mais com a lib. 
Espero em breve poder anunciar essas novidades.

2021-11-07 05:08 UTC, cclauss commented
Great!  Is there any problem with merging these changes while we wait, for your improvements?

2022-01-26 12:36 UTC, leotada commented
@cclauss Acredito que as partes de compatibilidade com código de Python 2 podem ser removidas do seu PR. E conflitos corrigidos.

2022-01-26 14:47 UTC, leogregianin commented on run_fake_soap_server.py
> -    tornado.ioloop.IOLoop.instance().start()
O arquivo run_fake_soap_server.py não mais existe.

2022-01-26 14:48 UTC, leogregianin commented on run_tests.py
> -    print 'Finished!'
O arquivo run_tests.py não mais existe.

2022-01-26 14:48 UTC, leogregianin requested changes
@cclauss, sua branch ainda está com conflitos.

2022-01-26 15:03 UTC, cclauss commented
Output: https://github.com/cclauss/PyNFe/actions
* `basestring` and `unicode` were both removed in Python 3.

2022-01-26 16:19 UTC, leogregianin commented
> Output: https://github.com/cclauss/PyNFe/actions
> 
> * `basestring` and `unicode` were both removed in Python 3.

Eu criei esse PR #142 para corrigir isso.

2022-01-29 04:14 UTC, juniortada commented
Fix in PR #144

2022-01-29 04:14 UTC, closed without merging