Ajuste tag cInt como opcional e formatação vCarga
TadaSoftware/PyNFe pull request #243
Opened 2022-11-17 19:48 UTC by AlexandreLumertz

> cInt opcional
> vCarga formato

2022-11-18 12:03 UTC, leogregianin approved these changes

2022-11-18 12:06 UTC, juniortada approved these changes

2022-11-18 21:36 UTC, leogregianin commented
@AlexandreLumertz seu último commit não passou nos testes.
Nos testes tem que informar o dado bruto conforme vem no XML, por exemplo, nesse caso, `1000.00`.

2022-11-18 21:37 UTC, leogregianin requested changes

2022-11-18 21:37 UTC, leogregianin commented on tests/test_mdfe_serializacao.py
> -        self.assertEqual(vCarga, '1000')
@AlexandreLumertz seu último commit não passou nos testes.
Nos testes tem que informar o dado bruto conforme vem no XML, por exemplo, nesse caso, 1000.00.

2022-11-18 21:38 UTC, leogregianin requested changes

2022-11-18 21:38 UTC, leogregianin commented on tests/test_mdfe_serializacao.py
> +        self.assertEqual(vCarga, str('{:.2f}').format('1000'))
@AlexandreLumertz seu último commit não passou nos testes.
Nos testes tem que informar o dado bruto conforme vem no XML, por exemplo, nesse caso, 1000.00.

2022-11-23 12:28 UTC, merged

2022-11-23 12:30 UTC, leogregianin commented
Legal @AlexandreLumertz, obrigado 🚀