FIX: vTotTrib não esta sendo formatado corretamente.
TadaSoftware/PyNFe pull request #315
Opened 2023-12-18 12:06 UTC by betogd

FIX: Corrigido problema de exception com mensagem vazia quando o campo `cliente.inscricao_estadual`esta nulo e o `indidacador_ie` != 2 ou `not client.isento_icms`, tornando dificil a identificação doi problema.

FIX: NFC-e deve permitir informar apenas o CPF e o Nome, no entanto não estava sendo gerado o nome do destinatario caso informado.

FIX: removido validação incorreta onde não permitia PIS/COFINS para NFC-e

ADDED: adicionado tag EXTIPI na serialização do XML

REFACTORY: removido prop `pis_situacao_tributaria` não utilizada no objeto `NotaFiscalProduto` e adicionado `pis_modalidade` que é utilizado pela serialização, esta incongruencia gerava confusão na hora de informar os dados do pis.

2024-01-02 21:43 UTC, juniortada commented on pynfe/processamento/serializacao.py
> +            etree.SubElement(raiz, "xNome").text = cliente.razao_social
Isso aqui está errado, deve permitir preencher somente cpf sem nome.

2024-01-02 21:44 UTC, juniortada commented on pynfe/processamento/serializacao.py
> +            etree.SubElement(imposto, "vTotTrib").text = "{:.2f}".format(
Valor de total de tributos deve ser informado pelo emissor.

2024-01-02 21:46 UTC, juniortada commented
Existe PIS e COFINS para NFC-e?

2024-02-23 00:42 UTC, felps-dev requested changes
Muito boas alterações! Somente alguns comentários importantes.

2024-02-23 00:42 UTC, felps-dev commented on pynfe/entidades/notafiscal.py
> +        return self.__totais_tributos_aproximado
Não entendi, por que foi feito isso?

2024-02-23 00:42 UTC, felps-dev commented on pynfe/entidades/notafiscal.py
> -        # self.totais_tributos_aproximado += obj.tributos
Não é a mesma coisa que antes?

2024-02-23 00:42 UTC, felps-dev commented on pynfe/entidades/notafiscal.py
> -    pis_situacao_tributaria = str()
Muito bem observado, isso aqui estava com o nome errado kkkk

2024-02-23 00:42 UTC, felps-dev commented on pynfe/processamento/serializacao.py
> +            etree.SubElement(raiz, "xNome").text = cliente.razao_social
ˆ Concordo.

2024-02-23 00:42 UTC, felps-dev commented on pynfe/processamento/serializacao.py
> +        ) or (cliente.inscricao_estadual or '').upper() == "ISENTO":
Acho que o certo é colocar um Throw se tentar colocar o inscricao_estadual como None OU no __init__ da classe preencher ele como "" caso for None.

2024-02-23 00:42 UTC, felps-dev commented on pynfe/processamento/serializacao.py
> +            etree.SubElement(imposto, "vTotTrib").text = "{:.2f}".format(
ˆ Mas está certo, a unica coisa que ele fez foi colocar a formatação padrão utilizada em outros valores decimais.

2024-02-23 00:42 UTC, felps-dev commented
> Existe PIS e COFINS para NFC-e?

Sim, são opcionais mas existem.

2024-04-27 02:23 UTC, juniortada commented
As alterações solicitadas não foram respondidas. Estou fechando este PR por enquanto.

2024-04-27 02:23 UTC, closed without merging

2024-06-13 22:07 UTC, betogd commented
> Existe PIS e COFINS para NFC-e?

existe a criterio da UF.