Update certificado.py
TadaSoftware/PyNFe pull request #335
Opened 2024-04-10 22:39 UTC by luizhcrivelli

Este pull request visa otimizar o load do certificado. Agora, o código irá verificar se a variavel recebida  já está carregada em memória em formato binário, como quando armazenado diretamente em um campo binario de um banco de dados. 

Se o certificado estiver nesse formato, o código fará a leitura diretamente do binário. 
Caso contrário (se o certificado for fornecido como uma string), o código manterá a leitura de um arquivo.

2024-04-20 05:12 UTC, felps-dev reviewed
Excelente, pode adicionar esse caso nos testes?

2024-04-20 05:12 UTC, felps-dev commented on pynfe/entidades/certificado.py
> +                ) from exc
Creio que esse try precise ficar antes do if, todo o carregamento precisa ter o try-catch.

2024-04-25 14:54 UTC, leotada commented
Faz mais sentido adicionar outro parâmetro no construtor com um nome que faça sentido, ao certificado binário já carregado, e valor default None.

2024-04-25 14:59 UTC, leotada requested changes
Faz mais sentido adicionar outro parâmetro no construtor com um nome que faça sentido, ao certificado binário já carregado, e valor default None, do que passar um binário no caminho_arquivo.

2025-01-07 21:04 UTC, felps-dev commented
Fechado por inatividade.

2025-01-07 21:04 UTC, closed without merging